version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    environment:
      NODE_ENV: TST
      AWS_REGION: us-west-2
    docker:
    # Image tags available here: https://circleci.com/docs/2.0/docker-image-tags.json
    - image: circleci/node:14.17.3
    steps:
    - checkout

    # Build
    - run: npm install
    - run: npm run build

    # Deployment
    - aws-s3/sync:
        # arguments: --acl public-read --cache-control "max-age=86400"
        from: public
        to: 's3://test.bigroom.eco/'
