version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
workflows:
 version: 2
 test:
   jobs:
     - build:
        context: TEST
        bucket: 's3://test.bigroom.eco/'
        filters:
          branches:
            only: master
 production:
   jobs:
     - build:
        context: PROD
        bucket: 's3://bigroom.eco/'
        filters:
          branches:
            only: production
jobs:
  build:
    parameters:
      bucket:
        type: string
    docker:
    # https://hub.docker.com/r/cimg/node
    - image: cimg/node:lts
    steps:
    - checkout

    # Build
    - run: sudo apt update
    - run: npm ci
    - run: npm run build
    - run: npm run minify

    # Deployment
    - aws-cli/setup
    - run: aws s3 sync public << parameters.bucket >> --exclude "*.webp"
    - run: aws s3 sync public << parameters.bucket >> --exclude "*.*" --include "*.webp" --content-type "image/webp"
